name: BuildRelease
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build_chrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the manifest
      run: python3 buildManifest.py
  build_firefox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the manifest
      run: python3 buildManifest.py --firefox
  
