name: BuildRelease
on:
  push:
    branches: [ dev ]
    tags: [ v* ]
jobs:
  build_chrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print env
      run: env
    - name: Build the manifest
      run: python3 build.py
    - name: Echo Manifest
      run: cat manifest.json
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        path: build/    
  build_firefox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the manifest
      run: python3 build.py --firefox
  
