name: BuildRelease
on:
  push:
    branches: [ dev ]
    tags: [ v* ]
jobs:
  build_chrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print env
      run: env
    - name: Build the manifest
      run: python3 build_and_release.py
  build_firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the manifest
        run: python3 build_and_release.py --firefox
